apiVersion: v1
kind: Service
metadata:
  name: orbital-fastapi
  labels:
    app.kubernetes.io/name: orbital-fastapi
    app.kubernetes.io/part-of: orbital-control-platform
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: orbital-fastapi
  ports:
    - name: http
      port: 8000
      targetPort: http
