#!/usr/bin/env bash
set -euo pipefail

PROJECT_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "${PROJECT_ROOT}"

NMC_BIN="${NMC_BIN:-${PROJECT_ROOT}/build/nmc}"
SEED="${SEED:-7}"
STAMP="$(date +%Y%m%d_%H%M%S)"
REPORT="${REPORT:-docs/performance/latest-device-benchmark.md}"
export CUBLAS_WORKSPACE_CONFIG="${CUBLAS_WORKSPACE_CONFIG:-:4096:8}"

if [[ ! -x "${NMC_BIN}" ]]; then
  echo "[compare_devices] nmc binary not found at ${NMC_BIN}" >&2
  exit 1
fi

run_benchmark() {
  local device="$1"
  local name="device_${device}_${STAMP}"
  "${NMC_BIN}" benchmark --quick --device "${device}" --name "${name}" --seed "${SEED}"
  printf '%s\n' "artifacts/benchmarks/latest.json"
}

CPU_JSON="$(run_benchmark cpu | tail -n 1)"
cp "${CPU_JSON}" "/tmp/orbital-device-cpu-${STAMP}.json"

AUTO_JSON="$(run_benchmark auto | tail -n 1)"
cp "${AUTO_JSON}" "/tmp/orbital-device-auto-${STAMP}.json"

CUDA_STATUS="unavailable"
if "${NMC_BIN}" benchmark --quick --device cuda --no-cuda-fallback --name "device_cuda_${STAMP}" --seed "${SEED}"; then
  cp "artifacts/benchmarks/latest.json" "/tmp/orbital-device-cuda-${STAMP}.json"
  CUDA_STATUS="available"
fi

export STAMP REPORT CUDA_STATUS
python3 - <<'PY'
from __future__ import annotations

import json
import os
from pathlib import Path

stamp = os.environ["STAMP"]
report = Path(os.environ["REPORT"])
cuda_status = os.environ["CUDA_STATUS"]

paths = {
    "cpu": Path(f"/tmp/orbital-device-cpu-{stamp}.json"),
    "auto": Path(f"/tmp/orbital-device-auto-{stamp}.json"),
}
if cuda_status == "available":
    paths["cuda"] = Path(f"/tmp/orbital-device-cuda-{stamp}.json")

rows = []
for requested, path in paths.items():
    data = json.loads(path.read_text(encoding="utf-8"))
    runtime = data["eval"]["runtime"]
    perf = data["performance"]
    rows.append(
        (
            requested,
            runtime["compute_backend_resolved"],
            runtime["torch_device"],
            runtime["cuda_fallback_used"],
            data["eval"]["avg_episode_return"],
            perf["eval_avg_inference_latency_ms"],
            perf["eval_p50_inference_latency_ms"],
            perf["eval_p95_inference_latency_ms"],
        )
    )

lines = [
    "# Latest Device Benchmark",
    "",
    f"Generated by `scripts/compare_devices.sh` with seed `{os.environ.get('SEED', '7')}`.",
    "",
    "This is a smoke-scale comparison, not a production performance claim. CUDA rows only appear when CUDA is actually available.",
    "",
    "| Requested | Resolved | Torch device | CUDA fallback | Avg return | Avg latency ms | P50 ms | P95 ms |",
    "| --- | --- | --- | --- | ---: | ---: | ---: | ---: |",
]
for row in rows:
    lines.append(
        f"| `{row[0]}` | `{row[1]}` | `{row[2]}` | `{str(row[3]).lower()}` | "
        f"{row[4]:.5f} | {row[5]:.7f} | {row[6]:.7f} | {row[7]:.7f} |"
    )
if cuda_status != "available":
    lines.extend(["", "**CUDA unavailable:** the explicit CUDA benchmark failed cleanly; no CUDA acceleration is claimed."])

lines.extend(
    [
        "",
        "## Separate Historical CUDA Functional Validation",
        "",
        "A separate strict CUDA smoke train and evaluation completed on June 10, 2026 using an NVIDIA GeForce RTX 4050 Laptop GPU, CUDA Toolkit 12.5, and CUDA-enabled LibTorch cu124:",
        "",
        "- training runtime: `requested=cuda`, `resolved=cuda:0`, `fallback=false`",
        "- evaluation runtime: `libtorch_cuda`, `uses_cuda=true`, `fallback=false`",
        "- strict artifact validation and CTest passed after the run",
        "",
        "That validation confirms functional execution on the named local machine. It is separate from the table above, does not establish a CPU-versus-CUDA speedup, and does not claim native TensorRT acceleration.",
    ]
)

report.parent.mkdir(parents=True, exist_ok=True)
report.write_text("\n".join(lines) + "\n", encoding="utf-8")
print(report)
PY
